name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      run:  |
        echo "iniciando login"
        docker login -u  $DOCKER_USER -p $DOCKER_PASSWORD
        echo "iniciando fin login"
 #   - name: Build the Docker image
 #     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build Docker Image
      run:  |
        docker build -t thunder609/docker-graphql:0.1.1   
    - name: Push Docker Image
      run:  |
        docker push thunder609/docker-graphql:0.1.1   